name: Deploy to Hostinger

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Hostinger
        uses: SamKirkland/FTP-Deploy-Action@v4.3.0
        with:
          server: mosaichostels.com
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./
          exclude: |
            **/.git*
            **/.github
            **/images/unused/
            **/.DS_Store
            **/node_modules/
